config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :bookings, only: [:index, :edit, :update, :destroy, :show]
  resources :lairs do
    resources :bookings, only: [:new, :create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :lair
  belongs_to :user

  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :rating, allow_nil: true, numericality: { only_integer: true, in: 0..5 }

  validate :check_out_after_check_in

  def check_out_after_check_in
    return if check_out.blank? || check_in.blank?

    begin
      if check_out <= check_in
        errors.add(:check_out, "must be after the check-in date")
      end
    rescue ArgumentError
      errors.add(:base, "Invalid date format for check-in or check-out")
    end
  end
end

app/models/lair.rb
class Lair < ApplicationRecord
  has_many_attached :images
  belongs_to :user

  has_many :bookings, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 5 }
  validates :location, presence: true
  validates :average_rating, allow_nil: true, numericality: { only_integer: true, in: 0..5 }
  validates :max_guests, numericality: { only_integer: true, greater_than: 0 }
  validates :price_per_night, numericality: { greater_than: 0 }

  include PgSearch::Model
  pg_search_scope :search_lairs,
    against: [ :name, :description, :location, :description, :tagline ],
    using: {
      tsearch: { prefix: true },
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Owned lairs
  has_many :lairs, class_name: "Lair", dependent: :destroy

  # Rented lairs
  has_many :bookings, dependent: :destroy
  has_many :rented_lairs, through: :bookings, source: :lair
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :authorize_user, only: %i[ edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @lair = Lair.find(params[:lair_id])
    @booking = Booking.new(
      check_in: params[:check_in],
      check_out: params[:check_out]
    )
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @lair = Lair.find(params[:lair_id])
    @booking.lair = @lair
    if @booking.save!
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /bookings/1/edit
  def edit
  end


  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    @booking.update(booking_params)
    @lair = Lair.find(@booking.lair_id)
    lairs = Booking.where(lair_id: @lair.id)
    if @booking.rating
      @lair.average_rating = (lairs.sum(:rating)/lairs.count(:rating)).round
      @lair.save!
    end
    redirect_to lair_path(@booking.lair)
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:check_in, :check_out, :rating)
    end

    def authorize_user
      unless current_user == @booking.user
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to lairs_path
      end
    end
end

app/controllers/lairs_controller.rb
class LairsController < ApplicationController
  before_action :set_lair, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new create edit update destroy ]
  before_action :authorize_user, only: %i[ edit update destroy ]

  def index
    @lairs = if params[:query].present?
               Lair.search_lairs(params[:query])
             else
               Lair.all
             end

    if params[:check_in].present? && params[:check_out].present?
      check_in = Date.parse(params[:check_in])
      check_out = Date.parse(params[:check_out])

      @lairs = @lairs.select do |lair|
        lair.bookings.none? do |booking|
          booking_range = booking.check_in..booking.check_out
          booking_range.overlaps?(check_in..check_out)
        end
      end
    end

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # GET /lairs/1 or /lairs/1.json
  def show
    @lair = Lair.find(params[:id])
  end

  # GET /lairs/new
  def new
    @lair = Lair.new
  end

  # GET /lairs/1/edit
  def edit
  end

  # POST /lairs or /lairs.json
  def create
    @lair = Lair.new(lair_params)
    @lair.user = current_user
    if @lair.save!
      redirect_to lair_path(@lair)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /lairs/1 or /lairs/1.json
  def update
    respond_to do |format|
      if @lair.update(lair_params)
        format.html { redirect_to lair_path(@lair) }
        format.json # Follows the classic Rails flow and look for a create.json view
      else
        format.html { render "update-show", status: :unprocessable_entity }
        format.json # Follows the classic Rails flow and look for a create.json view
      end
    end
  end

  # DELETE /lairs/1 or /lairs/1.json
  def destroy
    @lair.destroy!
    redirect_to lairs_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lair
    @lair = Lair.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lair_params
    params.require(:lair).permit(:name, :description, :location, :max_guests, :price_per_night, :average_rating, images: [])
  end

  def authorize_user
    unless current_user == @lair.user
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to lairs_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_lair_image(lair_name)
    default_images = {
      "Volcano Lair" => image_path("volcano-lair.jpg"),
      "Fortress Vader" => image_path("fortress-2.jpg"),
      "Abandoned Amusement Park" => image_path("fun-house.jpg"),
      "Asteroid M" => image_path("asteroid-m.jpg"),
      "Barad-dûr" => image_path("barad-dur.jpg"),
      "Snake Mountain" => image_path("snake-mountain.jpg"),
      "Bowser's Castle" => image_path("bowsers-castle.jpg"),
      "Oscorp Penthouse" => image_path("oscorp-penthouse.jpg"),
      "Malfoy Manor" => image_path("malfoy-manor.jpg"),
      "Technodrome" => image_path("technodrome.jpg")
    }

    default_images[lair_name] || image_path("lair-placeholder.jpg")
  end
end

app/views/bookings/_form.html.erb
<div class="form-booking">
  <%= simple_form_for([@lair,@booking]) do |f| %>
  <%= f.input :check_in,
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>
  <%= f.input :check_out,
              as: :string,
              input_html: { data: { controller: "datepicker" } } %>

  <div>
    <%= f.button :submit, class: "form-btn" %>
  </div>
<% end %>
</div>

app/views/bookings/edit.html.erb
<div class="form-login p-5">
  <h1 class="pb-4">Editing booking</h1>

  <%= render "form", booking: @booking %>
</div>
<br>

<div>
  <%= link_to "Show this booking", @booking %> |
  <%= link_to "Back to bookings", bookings_path %>
</div>

app/views/bookings/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="bookings-container">
<h1>Bookings</h1>

<% if @bookings.empty? %>
  <div>
    <h3> You have no bookings yet. </h3>
    <%# <a class="neon-button" data-action="click->toggle#fire" id="no-bookings-button">Book Now!</a> %>
  </div>
<% end %>

<div id="bookings">
  <% @bookings.where(user_id: current_user).each do |booking| %>
    <%= link_to booking_path(booking) do %>
        <div class="card-product">
        <div class="bookings-image-container">
          <%if booking.lair.images.length > 0  %>
            <%= cl_image_tag images[0].key%>
          <%else %>
            <%= image_tag "#{default_lair_image(booking.lair.name)}" %>
          <%end%>
        </div>
          <div class="card-product-infos">
            <h2><%= booking.lair.name %></h2>
            <p><%= booking.lair.tagline %></p>
            <strong> Check-in:</strong> <%= booking.check_in%>
            <strong> Check-out: </strong> <%= booking.check_out %>
          </div>
        </div>
      <% end %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="page-container">
  <div class="form-new p-4">

    <h1>New booking</h1>

    <%= render "form", lair: @lair, booking: @booking %>

  </div>
  <%= image_tag "border.png", class: "page-border" %>
</div>
<%# <div class="mt-5">
  <%= link_to "Back to bookings", bookings_path %>
<%# </div> %>

app/views/bookings/show.html.erb
<p style="color: green"><%= notice %></p>
    <% date_today = Date.today %>

<% nights = @booking.check_out - @booking.check_in%>

<div class="your-booking-container">
  <h2> Your Booking : <h2>
  <div class="your-booking-card">
    <%if @booking.lair.images.length > 0  %>
      <%= cl_image_tag images[0].key%>
    <%else %>
      <%= image_tag "#{default_lair_image(@booking.lair.name)}" %>
    <%end%>
    <h1> <%= @booking.lair.name %></h1>
    <h3><%= @booking.lair.tagline %></h3>
    <p> Max occupancy: <%= @booking.lair.max_guests %></p>
    <p> <span>Location:</span> <%= @booking.lair.location %></p>
    <p> <span> Check-in:</span> <%= @booking.check_in%> </p>
    <p> <span> Check-out: </span> <%= @booking.check_out %> </p>
    <p> <span> Length of visit: </span> <%= nights %> </p>
    <p> <span>Total Cost: </span> £<%= format('%.2f', nights * @booking.lair.price_per_night) %> </p>
  </div>

  <% if date_today >= @booking.check_out %>
      <p><strong>Rate Your Visit:</strong>
    <%= form_with(model: [@lair,@booking], local: true) do |f| %>
      <div class="scull-rating">
        <% 5.downto(1) do |i| %>
          <%= f.radio_button :rating, i, id: "scull#{i}" %>
          <label for="scull<%= i %>" title="<%= i %> sculls">
            <i class="fa-solid fa-skull"></i>
          </label>
        <% end %>
      </div>
      <%= f.submit "Submit Rating" %>
    <% end %>
  <% end %>

  <div class="booking-btns-container">
    <%= link_to "Edit this booking", edit_booking_path(@booking), class: "book-button smaller-text" %> |
    <%= link_to "Back to bookings", bookings_path, class: "book-button smaller-text" %>
  </div>
    <%= button_to "Destroy this booking", @booking, method: :delete, class: " booking-delete-button smaller-text" %>

</div>

app/views/lairs/_banner.html.erb
<div class="hero-banner">
  <section class="carousel" aria-label="Hero Carousel">
    <div class="carousel__viewport">
      <div class="carousel__slide" id="slide1">
        <img src="/assets/lair1.jpg" alt="Lair 1" class="carousel-image">
      </div>
      <div class="carousel__slide" id="slide2">
        <img src="/assets/lair2.jpg" alt="Lair 2" class="carousel-image">
      </div>
      <div class="carousel__slide" id="slide3">
        <img src="/assets/lair3.jpg" alt="Lair 3" class="carousel-image">
      </div>
      <div class="carousel__slide" id="slide4">
        <img src="/assets/lair4.jpg" alt="Lair 4" class="carousel-image">
      </div>
      <div class="carousel__slide" id="slide5">
        <img src="/assets/lair5.jpg" alt="Lair 5" class="carousel-image">
      </div>
      <div class="carousel__slide" id="slide6">
        <img src="/assets/lair6.jpg" alt="Lair 6" class="carousel-image">
      </div>
      <div class="carousel__slide" id="slide7">
        <img src="/assets/lair7.jpg" alt="Lair 7" class="carousel-image">
      </div>
    </div>
    <%# <a href="#slide4" class="carousel__prev" aria-label="Previous Slide"></a> %>
    <%# <a href="#slide2" class="carousel__next" aria-label="Next Slide"></a> %>

  </section>
  <div class="text-container">
    <div class="hero-text">
      <h1>Still plotting in a cave? Pathetic.</h1>
      <p>Upgrade your villainy today.</p>
    </div>
  </div>
  <a class="neon-button" style="cursor: pointer;" data-action="click->toggle#fire">Book Now!</a>
</div>

app/views/lairs/_form.html.erb
<div class="form-lair">

  <%= simple_form_for @lair do |f| %>

    <div class="d-flex justify-content-center">
      <div class="row g-4 col-6 d-flex flex-column">
        <%= f.label :name %>
        <%= f.label :tagline %>
        <%= f.label :description %>
        <%= f.label :location %>
        <%= f.label :max_guests %>
        <%= f.label :price_per_night %>
        <%= f.label :photo %>
      </div>

      <div class="row g-3 col-6">
        <%=  f.text_field :name %>
        <%= f.text_field :tagline %>
        <%= f.text_field :description %>
        <%= f.text_field :location %>
        <%= f.text_field :max_guests %>
        <%= f.number_field :price_per_night %>
        <%= f.input :images, as: :file, input_html: {multiple: true}, label: false %>

      </div>
      </div>

    </div>

    <div class="d-flex justify-content-center">
      <%= f.submit "Create Lair", class: "form-btn"%>
    </div>

  <% end %>
</div>

app/views/lairs/_lair.html.erb
<div id="<%= dom_id lair %>">
</div>

app/views/lairs/_rating_stars.html.erb
<% full_stars = rating.to_i %>
<% half_star = (rating - full_stars) >= 0.5 %>
<% empty_stars = 5 - full_stars - (half_star ? 1 : 0) %>

<div class="stars">
  <% full_stars.times do %>
    <i class="fa-solid fa-skull"></i>
  <% end %>

  <% if half_star %>
    <i class="fa-regular fa-skull"></i>
  <% end %>

  <% empty_stars.times do %>
    <i class="fa-regular fa-skull"></i>
  <% end %>
</div>

app/views/lairs/_testimonials.html.erb
<div class="page-ad" data-toggle-target="toggleableElement">
  <div class="ad-image-container">
    <h2>The Infernal Jacuzzi</h2>
    <%= image_tag 'infernal-jacuzzi.jpg', class: "ad-image" %>
  </div>
  <div class="details">
      <p>A cozy volcano lair with molten lava rivers, custom trapdoors, and a hot tub for post-evil relaxation. Comes with a complimentary shark tank. Villainy never felt this chic.</p>
      <ul class="lair-amenities">
        <li>Dramatic lighting for monologuing.</li>
        <li>Overly large red buttons that scream “DO NOT PRESS.”</li>
        <li>Henchmen break rooms (minions not included).</li>
      </ul>
    <div class="testimonials">
      <h3>"I’ve stayed in a lot of lairs, but this one? Top-notch. The screaming echoes perfectly through the halls, and the lava pit made my rival positively faint. Five skulls out of five.” — <strong>Baron Blight</strong></h3>
      <p>Yes, there’s a no-hero policy, but let’s be honest—they’re persistent little pests. We recommend adding extra turret defenses and an overly complicated trap system. You know, for fun."</p>
    </div>
    <div class="fineprint">
      <p>Cancellations made within 24 hours of the hero finding your lair will incur a full charge and a very sarcastic email.</p>
    </div>
  </div>
</div>

app/views/lairs/_update-form.html.erb
<div class="form-lair" data-toggle-target='form' >

  <%= simple_form_for @lair { data: { update_form_target: 'form', action: 'submit->update-form#update' } } do |f| %>


    <div class="d-flex justify-content-center">
      <div class="row g-4 col-6 d-flex flex-column">
        <%= f.label :name %>
        <%= f.label :description %>
        <%= f.label :location %>
        <%= f.label :max_guests %>
        <%= f.label :price_per_night %>
        <%= f.label :photo %>
      </div>

      <div class="row g-3 col-6">
        <%=  f.text_field :name %>
        <%= f.text_field :description %>
        <%= f.text_field :location %>
        <%= f.text_field :max_guests %>
        <%= f.number_field :price_per_night %>
        <%= f.input :images, as: :file, input_html: {multiple: true}, label: false %>

      </div>
      </div>

    </div>

    <div class="d-flex justify-content-center">
      <%= f.submit "Update Lair", class: "form-btn"%>
    </div>

  <% end %>
</div>

app/views/lairs/_updated_show.html.erb
<div data-update-form-target="container">
    <%= link_to "Book this lair", new_lair_booking_path(@lair, check_in: params[:check_in], check_out: params[:check_out]), class: "book-button" %>
  <div class="show-card">

    <h1> <%= @lair.name %></h1>

    <div class="show-img-carousel" data-controller="carousel">
      <section class="show-carousel" aria-label="Hero Carousel">
        <div class="show_viewport" data-carousel-target="viewport">
          <%if @lair.images.length > 1  %>
            <% @lair.images.each_with_index do |image, index| %>
              <div class="carousel__slide" data-carousel-target="slide" id="slide<%= index + 1 %>">
                <%= cl_image_tag image.key %>
              </div>
            <% end %>
          <% elsif @lair.images.length == 1 %>
            <%= cl_image_tag @lair.images.first.key %>
          <% else %>
            <%= image_tag("lair-placeholder.jpg") %>
          <% end %>
        </div>

        <a class="show__prev" data-action="carousel#prev" aria-label="Previous Slide"><i class="fas fa-chevron-left"></i></a>
        <a class="show__next" data-action="carousel#next" aria-label="Next Slide"><i class="fas fa-chevron-right"></i>
  </a>
      </section>
    </div>

    <h3><%= @lair.tagline %></h3>
    <p> <strong>Lair info:</strong> <%= @lair.description %></p>
    <p> <strong>Max occupancy:</strong> <%= @lair.max_guests %></p>
    <p> <strong>Location:</strong> <%= @lair.location %></p>
    <% if @lair.average_rating %>
      <p>
        <strong>Rating:</strong>
        <%= render 'lairs/rating_stars', rating: @lair.average_rating %>
      </p>
    <% end %>
    <p> <strong>Price: </strong> £<%= format("%.2f", @lair.price_per_night) %></p>

  </div>


  <div class="btns-container">
    <% if current_user == @lair.user %>

      <div data-controller="toggle">
        <button data-action="click->toggle#fire">Edit this Lair</button>
        <div class="show-form-edit d-none" data-toggle-target="toggleableElement">
          <h1>Edit Lair</h1>
          <%= render "form", lair: @lair %>
        </div>
      </div>
     <%= button_to "Destroy this lair", @lair, method: :delete %>

    <%end %>
  </div>

</div>

app/views/lairs/edit.html.erb
<div class="form-new">
  <h1>Editing lair</h1>

  <%= render "form", lair: @lair %>

  <div class="mt-2" >
    <%= link_to "Show this lair", lair_path %> |
    <%= link_to "Back to lairs", lairs_path %>
  </div>
</div>

app/views/lairs/index.html.erb
<div class="banner-search">
  <%= render 'lairs/banner' %>
  <div class="search-bar d-none" data-toggle-target="toggleableElement">

    <%= form_with url: lairs_path, method: :get, class: "d-flex", data: { controller: "search", action: "input->search#search", search_url: lairs_path } do %>
      <%= text_field_tag :query, params[:query], placeholder: "Search for a lair", data: { search_target: "query" } %>
      <%= text_field_tag :check_in, params[:check_in], placeholder: "Check-in", data: { search_target: "checkIn" } %>
      <%= text_field_tag :check_out, params[:check_out], placeholder: "Check-out", data: { search_target: "checkOut" } %>
    <% end %>
  </div>
</div>

<%= render 'lairs/testimonials' %>

<p style="color: green"><%= notice %></p>

<div class="index-container d-none" data-toggle-target="toggleableElement">
  <div id="lair-results" class="lairs-container">
    <% @lairs.each do |lair| %>
      <%= link_to lair_path(lair, check_in: params[:check_in], check_out: params[:check_out]) do %>
        <div class="lair-card">
          <div class="image-container">
<%if lair.images.length > 0  %>
              <%= cl_image_tag lair.images.first.key, class: "lair-image" %>
            <%else %>
              <%= image_tag "#{default_lair_image(lair.name)}" %>
            <%end%>
          </div>
          <h2><%= lair.name %></h2>
          <p><%= lair.tagline %></p>
          <div class="more-info">
            <p><i class="fa-solid fa-users-line"></i> <%= lair.max_guests %></p>
            <p><%= lair.price_per_night %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lairs/index.turbo_stream.erb
<%= turbo_stream.replace "lair-results" do %>
  <div id="lair-results" class="lairs-container">
    <% @lairs.each do |lair| %>
      <%= link_to lair_path(lair, check_in: params[:check_in], check_out: params[:check_out]) do %>
        <div class="lair-card">
          <div class="image-container">
     <%if lair.images.exists?  %>
              <%= cl_image_tag lair.images.first.key, class: "lair-image" %>
            <%else %>
              <%= image_tag "#{default_lair_image(lair.name)}", class: "lair-image" %>
            <%end%>
          </div>
            <h2><%= lair.name %></h2>
          <p><%= lair.tagline %></p>
          <div class="more-info">
            <p><i class="fa-solid fa-users-line"></i> <%= lair.max_guests %></p>
            <p>£<%= lair.price_per_night %>0</p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/lairs/new.html.erb
<div class="page-container">
<div class="form-new">
  <h1>New lair</h1>
  <%= render "form", lair: @lair %>
  </div>
  <%= image_tag "border.png", class: "page-border" %>
</div>
<%# <div class="mt-4">
  <%= link_to "Back to lairs", lairs_path %>
<%# </div> %> 

app/views/lairs/show.html.erb
<div class="show-container">
  <p style="color: green"><%= notice %></p>
</div>


<div data-controller="update-form" >
  <%= render 'updated_show', lair: @lair %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="copyright">
    <p>© 2025 Villains Inc.</p>
  </div>
  <div class="made-by">
    <p><i class="fa-solid fa-skull-crossbones"></i>This website was made by evil<i class="fa-solid fa-skull-crossbones"></i></i></p>
  </div>
  <div class="socials">
  <ul>
    <li><a href="#"><i class="fa-solid fa-bomb"></i></a></li>
    <li><a href="#"><i class="fa-solid fa-skull"></i></a></li>
    <li><a href="#"><i class="fa-solid fa-ghost"></i></a></li>
  </ul>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="navbar-logo">
    <%= link_to root_path do %>
      <%= image_tag 'house-logo.png', class: "logo" %>
    <% end %>
    <div class="page-title">
      <h1>VillainouS VillaS</h1>
    </div>
  </div>
  <div class="menu">
    <ul class="navbar-links">
      <li><a href="<%= lairs_path %>">Home</a></li>
      <% if user_signed_in? %>
        <li><a href="<%= new_lair_path %>">New Lair</a></li>
        <%= link_to "My Bookings", bookings_path %>
        <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
      <% else %>
        <li><a href="<%= new_user_session_path  %>"> Login</a></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VillanousVillas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Amarante&family=Glass+Antiqua&family=Metal+Mania&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/54697ea06b.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% unless controller_name == 'pages' && action_name == 'home' %>
      <%= render 'layouts/navbar' %>
    <% end %>
    <% if notice.present? %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <div class="content" data-controller="toggle" data-toggle-target="form">
      <%= yield %>
    </div>
    <% unless controller_name == 'pages' && action_name == 'home' %>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="video-container" data-controller="button-sound">
  <video autoplay muted loop id="bg-video">
    <source src="<%= asset_path('haunted_bg_2.mp4') %>" type="video/mp4">
  </video>

  <div class="overlay-content">
    <h1>Villainous Villas</h1>
    <p>Because every villain deserves a lair that screams ‘I’m better than you.’</p>
       <%= link_to "Explore Lairs", lairs_path, class: "btn", id: "click-me",
      data: { "audio-path": asset_path('evil_laugh.mp3'),
              action: "click->button-sound#play",
              buttonSoundTarget: "btn" } %>

  </div>
</div>